# welcome to numpy

In [1]:
import numpy as np

In [2]:
myarr=np.array([3,6,55,4],np.int8)#where np.int is to handle memory space

In [3]:
myarr[0]#this will show error if myarr[0,3] so..

3

In [4]:
myarr=np.array([[3,6,55,4]],np.int8)#..thats why double sq brackets is used

In [5]:
myarr[0,3]

4

In [6]:
myarr[0,3]=99 #for changing element

In [7]:
myarr

array([[ 3,  6, 55, 99]], dtype=int8)

#myarr.shape #this will show number of rows and columns

In [8]:
myarr.dtype#this will show the type

dtype('int8')

In [9]:
#for further search numpy type reference...

# Array creation : conversion from other python languages

In [10]:
listarray=np.array([[1,2],[3,4],[5,6]])

In [11]:
listarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.size

6

In [14]:
listarray.shape

(3, 2)

In [15]:
zeros=np.zeros((3,3))

In [16]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
zeros.shape

(3, 3)

In [18]:
zeros.dtype

dtype('float64')

In [19]:
zeros.size

9

In [20]:
rng = np.arange(15) #will arrange

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
lspace=np.linspace(1,5,4) #1 se le kar  5  ko 4 hisson mai divide kardo ye matlb hua iska

In [23]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [24]:
emp=np.empty((4,6))

In [25]:
emp

array([[2.56761491e-312, 2.41907520e-312, 1.93101617e-312,
        1.97345609e-312, 2.46151512e-312, 2.22809558e-312],
       [6.79038654e-313, 2.22809558e-312, 2.29175545e-312,
        2.44029516e-312, 2.35541533e-312, 6.79038654e-313],
       [2.41907520e-312, 2.35541533e-312, 6.79038654e-313,
        2.16443571e-312, 2.31297541e-312, 2.05833592e-312],
       [2.41907520e-312, 1.01855798e-312, 1.08221785e-312,
        6.79038654e-313, 2.35541533e-312, 9.76118064e-313]])

In [26]:
emp_like = np.empty_like(myarr) #myarr is liye daala kiu ke yaha ap kesi ki bhi alue daal sakhte

In [27]:
emp_like

array([[0, 0, 0, 0]], dtype=int8)

In [28]:
ide=np.identity(45)

In [29]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [30]:
ide.shape

(45, 45)

In [31]:
arr=np.arange(99)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr.reshape(3,33) #33 isliye liye kiu ke 3 multiply karke 99 hi aayega(divided number choose karna)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [34]:
arr=arr.ravel() #ravel will combine

In [35]:
arr.shape #(99,) is a 1D array

(99,)

In [36]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [37]:
arr = np.array(x)

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr.sum(axis=0) #axis zero(0) is vertical

array([12, 15, 18])

In [40]:
arr.sum(axis=1)#axis one(1) is horizontal

array([ 6, 15, 24])

In [41]:
arr.T # T is case sensitive

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
arr.flat

In [43]:
for item in arr.flat:
   print(item)

1
2
3
4
5
6
7
8
9


In [44]:
arr.ndim #will show 2 bcz numer of dimensions are 2

2

In [45]:
arr.size #size of elements

9

In [46]:
arr.nbytes #will show total bytes consumed

36

In [47]:
one =np.array([1,2,3,44,11])

In [48]:
one.argmax() # we use () bcz this time we use this commad as a function
             #showed 3 bcz max value was at 3

3

In [49]:
one.argmin() #showed 0 bcz max value was at 0

0

In [50]:
one.argsort() #this is showing sorted indexes

array([0, 1, 2, 4, 3], dtype=int64)

In [51]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr.argmin()

0

In [53]:
arr.argmax()

8

In [54]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [55]:
arr.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [56]:
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [57]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [58]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr.shape

(3, 3)

In [60]:
arr2 = np.array([[0,22,3],
                [4,11,6],
                [7,44,5]])

In [61]:
arr+arr2

array([[ 1, 24,  6],
       [ 8, 16, 12],
       [14, 52, 14]])

In [62]:
arr*arr2

array([[  0,  44,   9],
       [ 16,  55,  36],
       [ 49, 352,  45]])

In [63]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [64]:
np.where(arr>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [65]:
type(np.where(arr>5))

tuple

In [66]:
np.count_nonzero(arr)

9

In [67]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [68]:
arr[1,2]=0 #will replace

In [69]:
import sys

In [70]:
py_arr=[0,5,54,2]

In [71]:
np_arr=np.array(py_arr)

In [72]:
sys.getsizeof(1) * len(py_arr)

112

In [73]:
np_arr.itemsize * np_arr.size

16